#!/bin/bash

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

PANELDIR=$HOME/.config/panel
DATA=$PANELDIR/paneldata.txt

DIMENSIONS="x22"
FONT1="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
FONT2="-*-stlarch-medium-r-normal-*-10-*-*-*-c-*-*-1"
#FONT1="-*-tewi-medium-r-normal-*-11-*-*-*-*-*-*-1"
UNDERLINE="2"
BG="#ff232323"
FG="#ffc5c8c6"

if [ -e $DATA ]; then
    rm $DATA
fi
mkfifo $DATA

conky -c $PANELDIR/panelconky > $DATA &
bspc control --subscribe > $DATA &

$PANELDIR/panel_parse < $DATA | bar -b -g $DIMENSIONS -f $FONT1,$FONT2 -u $UNDERLINE -B $BG -F $FG | sh #pipe into sh for fancy commands
