#!/bin/bash

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

PANELDIR=$HOME/.config/panel
DATA=$PANELDIR/paneldata.txt

DIMENSIONS="1856x32+32+32"
FONT1="Monospace:size=10:Bold"
FONT2="-*-stlarch-medium-r-normal-*-10-*-*-*-c-*-*-1"
#FONT1="-*-tewi-medium-r-normal-*-11-*-*-*-*-*-*-1"
UNDERLINE="2"
BG="#fff5f5f5"
FG="#ff303030"

if [ -e $DATA ]; then
    rm $DATA
fi
mkfifo $DATA

#conky -c $PANELDIR/panelconky > $DATA &
bspc subscribe > $DATA &
while true; do
	echo "S:%{c}$(date '+%A, %B %-d %-I:%M')%{r}%{A:session-exit:}$(whoami)@$(hostname) %{A} %{F#ff6fc2ef B-}▲  "
	sleep 1m
done > $DATA &

$PANELDIR/panel_parse < $DATA | lemonbar -g $DIMENSIONS -f $FONT1 -f $FONT2 -u $UNDERLINE -B $BG -F $FG | sh #pipe into sh for fancy commands
