#! /bin/bash

bspc config bottom_padding 22

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        1
bspc config window_gap          16 
bspc config split_ratio         0.52

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate false
bspc config auto_cancel true
bspc config focused_border_color "#7fa6d7"
bspc config presel_border_color "#cdd9e7"

#rules
bspc rule -a "Pidgin" "floating=on"
bspc rule -a "Wine" "floating=on"
bspc rule -a "Steam" "floating=on"
bspc rule -a "Galculator" "floating=on"
bspc rule -a "gimp" "floating=on"
bspc rule -a "feh" "floating=on"
bspc rule -a "Desmume" "floating=on"

#panel
$HOME/.config/panel/panel &
