#! /bin/bash

source $HOME/.bash_profile

hsetroot -solid '#fb9fb1'

xset m 3/2 0 #mouse speed
xset r rate 250 30 #keyboard repeat rate
setxkbmap -layout us -variant mac -option numpad:mac #fix the damn numpad
sxhkd & #key bindings
compton & #pretty windows
urxvtd -q -f -o #terminal daemon in background no & because --fork option is set
xrdb ~/.Xresources #xresources for pointer and urxvt colors and stuff
xsetroot -cursor_name left_ptr & #not stupid cursor
xset +fp /usr/share/fonts/local
xset fp rehash
xinput --set-prop "pointer:Logitech M510" "Evdev Scrolling Distance" -1 -1 1
dropbox & #dropbox duh
unclutter &
xautolock -detectsleep -time 15 -locker "pixellock" &

bspc config border_width        3
bspc config window_gap          32
bspc config split_ratio         0.55

bspc config top_padding 64

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_follows_pointer true
bspc config focused_border_color "#b0b0b0"
bspc config presel_feedback_color "#b0b0b0"
bspc config normal_border_color "#e0e0e0"

#rules
bspc rule -a Pidgin state=floating
bspc rule -a Wine state=floating
bspc rule -a Steam state=floating
bspc rule -a Galculator state=floating
bspc rule -a gimp state=floating
bspc rule -a feh state=floating
bspc rule -a lighthouse manage=off
#bspc rule -a "vlc" "pseudo_tiled=on"

#Start my panel
$HOME/.config/panel/panel &
