#! /bin/bash

source $HOME/.bash_profile

hsetroot -full $HOME/.config/pics/balloon.png #set background

xset m 3/2 0 #mouse speed
xset r rate 250 30 #keyboard repeat rate
setxkbmap -layout us -variant mac -option numpad:mac #fix the damn numpad
sxhkd & #key bindings
compton & #pretty windows
urxvtd -q -f -o #terminal daemon in background no & because --fork option is set
xrdb ~/.Xresources #xresources for pointer and urxvt colors and stuff
xsetroot -cursor_name left_ptr & #not stupid cursor
xset +fp /usr/share/fonts/local
xset fp rehash
xinput --set-prop "pointer:Logitech M510" "Evdev Scrolling Distance" -1 -1 1
dropbox & #dropbox duh
unclutter &
xautolock -detectsleep -time 15 -locker "pixellock" &

bspc config border_width        1
bspc config window_gap          16
bspc config split_ratio         0.55

bspc config bottom_padding 22

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate false
bspc config auto_cancel true
bspc config focused_border_color "#7fa6d7"
bspc config presel_border_color "#cdd9e7"
bspc config focused_sticky_border_color "#6185b6"

#rules
bspc rule -a Pidgin floating=on
bspc rule -a Wine floating=on
bspc rule -a Steam floating=on
bspc rule -a Galculator floating=on
bspc rule -a gimp floating=on
bspc rule -a feh floating=on
bspc rule -a lighthouse manage=off
#bspc rule -a "vlc" "pseudo_tiled=on"

#Start my panel
$HOME/.config/panel/panel &
