#!/usr/bin/env bash

imagepath() {
    echo -n "%I$HOME/.config/lighthouse/$@.png%"
}

function autocomp {
    case $@ in
        ch*)
            image=googlechrome
            name=chrome
            run=google-chrome-stable
            ;;
        spotin*)
            image=spotify
            name=spotinterface
            run=spotinterface
            ;;
        sp*)
            image=spotify
            name=spotify
            run=spotify
            ;;
        lib*)
            image=libreoffice
            name=libreoffice
            run=libreoffice
            ;;
        ste*)
            image=steam
            name=steam
            run=steam
            ;;
    esac
    if [ -n "$name" ]
    then
        echo -n "{$(imagepath $image) $name|$run $(echo $@|sed 's/[^ ]* \?//')}"
    fi
    name=
}

function findexec {
    cmd=$(echo $@ | awk '{print $1}')
    if command -v $cmd 1>&2>/dev/null
    then
        echo -n "{execute $cmd|$@}"
        echo -n "{run $cmd in shell|urxvtc -e $@}"
    else
        guess=$(find `echo $PATH|sed 's/:/ /g'` -executable -not -type d -name "$@*" -printf %f -quit)
        if [ -n "$guess" ]
        then
            echo -n "{execute $guess|$guess}"
            echo -n "{run $guess in shell|urxvtc -e $guess}"
        fi
    fi
}

function findfile {
    IFS=$'\n' #for loop ignores spaces as delim
    for F in $(find ~/docs ~/downloads -type f | grep -m 32 "[^/]*/$@[^/]*$"); do
        #echo -n "{open `echo $F|sed s:/home/spencer/::`|mimeo \"$F\"}"
        echo -n "{open `trimwd 3 $F`|xdg-open $F}"
    done
    IFS=$' '
}

function web {
    if [[ $@ =~ (https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/? ]]
    then
        echo -n "{$(imagepath googlechrome) $@|google-chrome-stable $@}"
    else
        echo -n "{search $@|google-chrome-stable https://www.google.com/search?q=$(echo $@ | sed 's/ /+/g')}"
    fi
}

function evaluate {
    [[ $@ =~ ^[0-9.*/-+^%()]+$ ]] && echo -n "{ = $(echo $@ | bc)|}"
    #echo "$@" | grep -q "[0-9.*/-+^%()]*" && echo -n "{ = $(echo $@ | bc)|}"
}

while read L; do
    evaluate "$L"
    autocomp "$L"
    findexec "$L"
    web "$L"
    findfile "$L"
    echo
done
